/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RockPaperScissorsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "gameCount"
      | "games"
      | "getGame"
      | "getGameCount"
      | "protocolId"
      | "submitChoice"
      | "submitSystemChoice"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "gameCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "games", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitChoice",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSystemChoice",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "gameCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSystemChoice",
    data: BytesLike
  ): Result;
}

export interface RockPaperScissors extends BaseContract {
  connect(runner?: ContractRunner | null): RockPaperScissors;
  waitForDeployment(): Promise<this>;

  interface: RockPaperScissorsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  gameCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  games: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean] & {
        playerChoice: string;
        systemChoice: string;
        result: string;
        isCompleted: boolean;
      }
    ],
    "view"
  >;

  getGame: TypedContractMethod<
    [player: AddressLike],
    [
      [string, string, string, boolean] & {
        playerChoice: string;
        systemChoice: string;
        result: string;
        isCompleted: boolean;
      }
    ],
    "view"
  >;

  getGameCount: TypedContractMethod<[player: AddressLike], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitChoice: TypedContractMethod<
    [playerChoiceEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  submitSystemChoice: TypedContractMethod<
    [systemChoiceEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "gameCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean] & {
        playerChoice: string;
        systemChoice: string;
        result: string;
        isCompleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [string, string, string, boolean] & {
        playerChoice: string;
        systemChoice: string;
        result: string;
        isCompleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGameCount"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitChoice"
  ): TypedContractMethod<
    [playerChoiceEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitSystemChoice"
  ): TypedContractMethod<
    [systemChoiceEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
